# Stage 1: Build the frontend
FROM node:20-alpine AS frontend_builder

WORKDIR /app

COPY ./frontend/package*.json /app

RUN npm install

COPY ./frontend /app

RUN npm run build

# Stage 2: Build the backend
FROM node:20-alpine

WORKDIR /app

COPY ./backend/package*.json /app

RUN npm install

COPY ./backend /app

COPY --from=frontend_builder /app/dist /app/public

CMD ["npm","run","start"]